root_url = "https://vpm.vlang.io"
is_dev = true

[jwt]
secret = "some_very_secure_secret"

[github]
client_id = ""
secret = ""

[http]
port = 8081

[postgres]
host = "localhost"
port = 5433
user = "vpm"
password = "vpm"
db = "vpm"
