version: "3.9"
services:
  app:
    image: vpm
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "./config.toml:/app/config.toml"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: vpm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: {}
