version: "3.9"
services:
  app:
    container_name: vpm
    image: vpm
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "./config.toml:/app/config.toml"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: vpm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/database:/var/lib/postgresql/data

networks:
  vpm: