version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust

  vpm:
    build: .
    restart: always
    ports:
      - 8080:8080
    volume:
      - "./config.toml:/app/config.toml"
      
volumes:
  database: {}