version: "3.9"

services:
  vpm:
    container_name: vpm
    image: vpm
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "./config.toml:/vpm/config.toml"
    depends_on:
      - database

  migrate:
    image: migrate/migrate
    restart: on-failure:5
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://vpm@database:5432/vpm?sslmode=disable", "up"]
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vpm
      POSTGRES_USER: vpm
      # POSTGRES_PASSWORD: vpm
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/var/lib/postgresql/data
