version: "3.9"

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: on-failure:5
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel run

  vpm:
    container_name: vpm
    image: vpm
    build:
      dockerfile: Dockerfile
      args:
        - args=-prod
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - "./config.toml:/vpm/config.toml"
    depends_on:
      - database

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://vpm@database:5432/vpm?sslmode=disable", "up"]

  database:
    image: postgres:14-alpine
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_DB: vpm
      POSTGRES_USER: vpm
      # POSTGRES_PASSWORD: vpm
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data:/var/lib/postgresql/data
