[package]
name = "vpm"
author = "Anton Terisback <terisbackno@gmail.com>"
description = "Package manager from V Language"
license = "MIT"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vex = "0.3.5"
